# RENAME FILE TO 'config.yml'
bot:
  token: MTI1MTUyODU1Mzg2Mjc5MTMwOA.GeIAzn.gcZ3rgRiuf4PLQZfG-bF0Pg0EDVC6grCAOoaWw
  owner_ids:
    - 123456789123456789
    - 987654321987654321
  prefix: $
  default_bet: 100
  bonus_multiplier: 5 # bonus = default_bet * multiplier
  bonus_cooldown: 12 # Bonus every x hours
