# RENAME FILE TO 'config.yml'
bot:
  token: MTI0NTQyODk2MjQxMTE1MTQwMQ.GEeIjn.lDD6kG0eZWIDNeg-e_XKLMV0LwIKTH-XHzm3_w
  owner_ids:
    - 123456789123456789
    - 987654321987654321
  prefix: $
  default_bet: 100
  bonus_multiplier: 5 # bonus = default_bet * multiplier
  bonus_cooldown: 12 # Bonus every x hours
