# RENAME FILE TO 'config.yml'
bot:
  token: MTIyNTE3OTI4NDExMzcxOTI5Ng.Gkz0Ou.N9_H5NDCvemwt4lmmq4erv9SBadYfAebeHLRRY
  owner_ids:
    - 123456789123456789
    - 987654321987654321
  prefix: $
  default_bet: 100
  bonus_multiplier: 5 # bonus = default_bet * multiplier
  bonus_cooldown: 12 # Bonus every x hours
