# RENAME FILE TO 'config.yml'
bot:
  token: MTI0NjIzMjY5MDUxMjg5MTk3NQ.GT7cqD.cXY1Pi-bWcDo1mhdM3Wh_daAtrUQjNTDmW5M18
  owner_ids:
    - 123456789123456789
    - 987654321987654321
  prefix: $
  default_bet: 100
  bonus_multiplier: 5 # bonus = default_bet * multiplier
  bonus_cooldown: 12 # Bonus every x hours
