# RENAME FILE TO 'config.yml'
bot:
  token: MTIzODkzMDI1MzU0NDU1ODU5Mw.GTo8FY.KZghPJ2835lBy2jFWEX1yGadKcKt5E3-yWQe0A
  owner_ids:
    - 123456789123456789
    - 987654321987654321
  prefix: $
  default_bet: 100
  bonus_multiplier: 5 # bonus = default_bet * multiplier
  bonus_cooldown: 12 # Bonus every x hours
